### ISSUE TITLE
Δημιουργία Παράλληλου αρχείου translation.md

### ISSUE THREAD

**Issue by gkodosis** [zoekt/gfoss_article_by_dmst#2]
Θα βοηθούσε μήπως να δημιουργήσω και ένα αρχείο translation.md όπου θα περνάμε ό,τι γράφεται στο article.md απευθείας και στα αγγλικά?

**Comment by zoekt** [comment]
Η μετάφραση είναι καθαρά προαιρετική και δεν έχει ζητηθεί από τον κύριο Σπινέλλη. Ωστόσο, θεωρώ ότι θα ήταν πολύ χρήσιμη. Εάν το θες, κανένα πρόβλημα.

**Comment by MalvinaPap** [comment]
Πολύ καλή ιδέα, εξάλλου δεν είναι δύσκολο να γίνει αν έχουμε ήδη στα ελληνικά το άρθρο.
